global HW_type
global DHCP_option
global DNS_opcode
global DNS_replycode
global DNS_type
global DNS_class

HW_type = {
    1: "Ethernet",
    6: "IEEE 802 Networks",
    7: "ARCNET",
    11: "LocalTalk",
    12: "LocalNet",
    14: "SMDS",
    15: "Frame Delay",
    16: "Asynchronous Transger Mode(ATM)",
    17: "HDLC",
    18: "Fibre Channel",
    19: "Asynchronous Transger Mode(ATM",
    20: "Serail line"
}

DHCP_option = {
    0: "Pad",
    1: "Subnet Mask",
    2: "Time Offset",
    3: "Router",
    4: "Time Server",
    5: "Name Server",
    6: "Domain Server",
    7: "Log Server",
    8: "Quotes Server",
    9: "LPR Server",
    10: "Impress Server",
    11: "RLP Server",
    12: "Hostname",
    13: "Boot File Size",
    14: "Merit Dump File",
    15: "Domain Name",
    16: "Swap Server",
    17: "Root Path",
    18: "Extension File",
    19: "Forward On/Off",
    20: "SrcRte On/Off",
    21: "Policy Filter",
    22: "Max DG Assembly",
    23: "Default IP TTL",
    24: "MTU Timeout",
    25: "MTU Plateau	",
    26: "MTU Interface",
    27: "MTU Subnet",
    28: "Broadcast Address",
    29: "Mask Discovery",
    30: "Mask Supplier",
    31: "Router Discovery",
    32: "Router Request",
    33: "Static Route",
    34: "Trailers",
    35: "ARP Timeout",
    36: "Ethernet",
    37: "Default TCP TTL",
    38: "Keepalive Time",
    39: "Keepalive Data",
    40: "NIS Domain",
    41: "NIS Servers",
    42: "NTP Servers",
    43: "Vendor Specific",
    44: "NETBIOS Name Srv",
    45: "NETBIOS Dist Srv",
    46: "NETBIOS Node Type",
    47: "NETBIOS Scope",
    48: "X Window Font",
    49: "X Window Manager",
    50: "Address Request",
    51: "Address Time",
    52: "Overload",
    53: "DHCP Msg Type",
    54: "DHCP Server Id",
    55: "Parameter List",
    56: "DHCP Message",
    57: "DHCP Max Msg Size",
    58: "Renewal Time",
    59: "Rebinding Time",
    60: "Class Id",
    61: "Client Id",
    62: "NetWare/IP Domain",
    63: "NetWare/IP Option",
    64: "NIS-Domain-Name",
    65: "NIS-Server-Addr",
    66: "Server-Name",
    67: "Bootfile-Name",
    68: "Home-Agent-Addrs",
    69: "SMTP-Server",
    70: "POP3-Server",
    71: "NNTP-Server",
    72: "WWW-Server",
    73: "Finger-Server",
    74: "Finger-IRC-Server",
    75: "StreetTalk-Server",
    76: "STDA-Server",
    77: "User-Class",
    78: "Directory Agent",
    79: "Service Scope",
    80: "Rapid Commit",
    81: "Client FQDN",
    82: "Relay Agent Information",
    83: "iSNS",
    84: "REMOVED/Unassigned",
    85: "NDS Servers",
    86: "NDS Tree Name",
    87: "NDS Context",
    88: "BCMCS Controller Domain Name list",
    89: "BCMCS Controller IPv4 address option",
    90: "Authentication",
    91: "client-last-transaction-time option",
    92: "associated-ip option",
    93: "Client System",
    94: "Client NDI",
    95: "LDAP",
    96: "REMOVED/Unassigned",
    97: "UUID/GUID",
    98: "User-Auth",
    99: "GEOCONF_CIVIC",
    100: "PCode",
    101: "TCode",
    108: "IPv6-Only Preferred",
    109: "OPTION_DHCP4O6_S46_SADDR",
    112: "Netinfo Address",
    113: "Netinfo Tag",
    114: "DHCP Captive-Portal",
    115: "REMOVED/Unassigned",
    116: "Auto-Config",
    117: "Name Service Search",
    118: "Subnet Selection Option",
    119: "Domain Search",
    120: "SIP Servers DHCP Option",
    121: "Classless Static Route Option",
    122: "CCC",
    123: "GeoConf Option",
    124: "V-I Vendor Class",
    125: "V-I Vendor-Specific Information",
    126: "Removed/Unassigned",
    127: "Removed/Unassigned",
    128: "PXE - undefined (vendor specific)",
    129: "Call Server IP Address",
    130: "Discrimination String",
    131: "Remote Statistics Server IP Address",
    132: "802.1Q VLAN ID",
    133: "802.1Q L2 Priority",
    134: "Diffserv Code Poin",
    135: "HTTP Proxy For Phone Applications",
    150: "TFTP Server Address : Etherboot : GRUB Config",
    177: "Ether Boot PacketCable and CableHome",
    208: "PXELINUX Magic",
    209: "Configuration File",
    210: "Path Prefix",
    211: "Reboot Time",
    220: "Subnet Allocation",
    221: "Virtual Subnet Allocation",
    255: "END",
    256: "Unknow Option"
}

DNS_opcode = {
    0: "Standard query",
    1: "IQuery",
    2: "Status",
    3: "Unassigned",
    4: "Notify",
    5: "Update",
    6: "DNS Stateful Operations",
    7: "Unassigned",
    8: "Unassigned",
    9: "Unassigned",
    10: "Unassigned",
    11: "Unassigned",
    12: "Unassigned",
    13: "Unassigned",
    14: "Unassigned",
    15: "Unassigned"
}

DNS_replycode = {
    0: "NOERROR",
    1: "FORMERR",
    2: "SERVFAIL",
    3: "NXDOMAIN",
    4: "NOTIMP",
    5: "REFUSED",
    6: "YXDOMAIN",
    7: "XRRSET",
    8: "NOTAUTH",
    9: "NOTZONE"
}

DNS_type = {
    1: "A (Host Address)",
    2: "NS (02)",
    3: "MD (03)",
    4: "MF (04)",
    5: "CNAME (05)",
    6: "SOA (06)",
    7: "MB (07)",
    8: "MG (08)",
    9: "MR (09)",
    10: "NULL (10)",
    11: "WKS (11)",
    12: "PTR (Domain name pointer) (12)",
    13: "HINFO (13)",
    14: "MINFO (14)",
    15: "MX (15)",
    16: "TXT (16)",
    28: "AAAA (28)"
}

DNS_class = {
    1: "Internet",
    2: "Class Csnet (depreciated)",
    3: "Chaos",
    4: "Hesiod"
}